### ISSUE TITLE
你的blog都是利用什么时间写的

### ISSUE THREAD

**Issue by cloudsmithy** [godbasin/5-minutes-help#2]
看到你的blog很喜欢，自己blog搭建了几年一直没怎么好好更新过。我平时也不加班，偶尔折腾电子产品到半夜，感觉觉都不够睡，看到你这么的文章，想问下都是利用什么时间写出来的。

**Comment by godbasin** [comment]
目前来说，写文章主要是有感觉了就会写。
时间的话其实特别好解决，工作日的话下班后抽一两个小时，周末也有很多时间可以写的。很多时候我们觉得自己没有时间，但是挤挤都很多的，就像很多人其实每天都能挤出一两个小时打游戏的。

**Comment by cloudsmithy** [comment]
那这样的节奏你觉得紧吗？我今年刚刚毕业，也要学一大堆东西，当然不打游戏。实习那阵每天5点下班，然后买菜做饭收拾一阵就累到躺尸了。我还看了你的公众号，很佩服你技术学的好，也有闲情写写文章。你一天都怎么管理你的时间呢，我之前有时候会严格按照时间表走，然后对于临时计划会打乱很多事情。没有计划的话，就一天啥也干不了。但是有时候又会强迫自己抓紧每一丝时间，最后把自己搞的很累。针对这个有什么办法吗？

**Comment by godbasin** [comment]
刚毕业的时候我也会时间安排得很紧，不过那段时间自己对学习的热情很高，所以也不会觉得累。现在工作久了有时候会觉得想要放松下，一般这种情况我会允许自己不去想计划啊规划啊什么的，就做点喜欢的事情，和朋友聊聊天之类的。等状态缓过来之后，就会继续在空闲的时候看看书、学点东西、写写文章什么的。
我会阶段性地整理自己学到的东西，然后写成文章，其实最开始的目的主要是自己的记性不好，所以写下来后面比较容易翻到。写文章我觉得主要是建立个正反馈会比较容易坚持，比如满足感、成就感这些，对我来说的确有些时候觉得以前写过的东西有很大的帮助，也因此一直坚持下来了。

**Comment by cloudsmithy** [comment]
好的，谢谢~~~~看了你的经历，我觉得我也找回了些最初的热情。

**Comment by godbasin** [comment]
那就好~祝一切顺利呀~~
